---

- hosts: master
  strategy: debug
  vars_files:
    - 'group_vars/kube.yaml'
  gather_facts: false
  become: true
  
- import_playbook: prepare_nfs.yaml

- import_playbook: prepare_master.yaml

- import_playbook: prepare_workes.yaml

- import_playbook: install_jenkins.yaml
