---

- hosts: nfs
  #strategy: debug
  vars_files:
    - 'group_vars/kube.yaml'
    - 'group_vars/kube_nfs.yaml'
  gather_facts: false
  become: true
  
  roles:
    - role: prepare_hosts
    - role: install_nfs
      
