---

- hosts: master
  #strategy: debug
  vars_files:
    - 'group_vars/kube.yaml'
    - 'group_vars/kube_nodes.yaml'
    - 'group_vars/kube_master.yaml'
  gather_facts: false
  become: true
  
  roles:
    - role: prepare_hosts
    - role: prepare_nodes
      vars:
        swap_status: 'no'
    - role: install_master
