---

- name: 'instalo gestor de particiones'
  dnf:
    name: '{{ package_partition}}'
    state: present
  #-# become: yes
  #-# become_method: sudo
  when: 1==1

- name: Monto /dev/vdb
  mount:
    path: '{{ mount }}'
    src: '{{ mount }}'
    fstype: ext4
    state: present
  #-# become: yes
  #-# become_method: sudo  


- name: Creo particion ext4
  filesystem:
    fstype: ext4
    dev: '{{ mount }}'
  #-# become: yes
  #-# become_method: sudo

- name: Creo volumen fisico en grupo data_vg
  lvg:
    vg: data_vg
    pvs: '{{ mount }}'

- name: Creo volumen logico nfs_lv
  lvol:
    vg: /dev/data_vg
    lv: nfs_lv
    size: 100%FREE

- name: Creo particion xfs en volumen logico
  filesystem:
    fstype: xfs
    dev: /dev/data_vg/nfs_lv

- name: Creo directorios /srv/nfs
  file:
    path: /srv/nfs
    state: directory
    owner: root
    group: root
    mode: '1777'

- name: Agrego configuracion a  /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '/dev/data_vg/nfs_lv /srv/nfs xfs defaults 0 0'
    line: '/dev/data_vg/nfs_lv /srv/nfs xfs defaults 0 0'
    state: present