---
- name: Confifuramos masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true

- name: 'Copio archivo para config k8s.conf'
  copy:
    src: 'k8s.conf'
    dest: '/etc/sysctl.d/'

- name: Reiniciamos el firewall
  shell: firewall-cmd --reload
