---
- name: Seteo zona horaria
  timezone:
    name: '{{ timezone_name }}'

- name: instalar chrony
  dnf:
    name: chrony
    state: present
    update_cache: yes


- name: Iniciar Chrony
  systemd:
    daemon_reload: no
    state: started
    name: chronyd
    enabled: yes

- name: Ejecutar Timedatectl
  command: timedatectl set-ntp true


