---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins-namespace
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  #persistentVolumeReclaimPolicy: Retain #Es para que no se elimine cuando se reinica pods
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs
    server: #nfs_ip#


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-namespace
spec:
  storageClassName: nfs
  volumeName: jenkins-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi