---

- name: 'Copio archivo Deploy service_account.yaml'
  copy:
    src: 'service_account.yaml'
    dest: '{{ path_deploy_kube }}'
  
- name: Despliego Service Account
  command: 'kubectl apply -f {{ path_deploy_kube }}/service_account.yaml'
  register: result
  
- debug:
    msg: '{{ result }}'