---

- name: 'Configura los puertos para el worker'
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ ports_workers }}'

- name: Reiniciamos el servicio de firewall
  systemd:
    name: firewalld
    state: reloaded


