---

- name: Habilito ip workers
  firewalld:
    rich_rule: 'rule family=ipv4 source address={{ item }}/32 accept'
    permanent: yes
    state: enabled
  loop: '{{ workers_ips }}'

- name: Habilito ip para docker
  firewalld:
    rich_rule: 'rule family=ipv4 source address=172.17.0.0/16 accept'
    permanent: yes
    state: enabled

- name: Reiniciamos el servicio de firewall
  systemd:
    name: firewalld
    state: reloaded

- name: Reiniciamos el servicio de docker
  systemd:
    name: 'docker'
    state: reloaded
  
- name: Reinicio servicio de docker con command
  command: systemctl restart docker
  register: result
  
#- name: Espera 30 segundos - Reinicia dockers | NO FUNCIONA EN AZURE
#  wait_for:
#    timeout: 30
#  delegate_to: localhost

