---
- name: Obtengo token para unir nodo.
  command: 'kubeadm token create --print-join-command'
  register: kubeadm_token

- debug:
    msg: 'Comando a ejecutar : {{ kubeadm_token.stdout_lines[0] }}'

- debug:
    msg: 'Guardo token en archivo : {{ kube_admin_token_file }}'

- name: Guardo token master en archivo para workers
  local_action: copy content="{{ kubeadm_token.stdout_lines[0] }}" dest="{{ kube_admin_token_file }}"
  become: false
  run_once: true