---
- name: Agregar Ip a Hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.name }}$'
    line: '{{ item.ip }} {{ item.name }} {{ item.name_long }}'
    state: present
  with_items: '{{ var_hosts }}'
  
