---

- name: 'Configura los puertos para el worker'
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ ports_workers }}'

- name: 'Configura los puertos para el worker'
  firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
    zone: public
  loop: '{{ az_dns_ports_dns }}'

- name: Reiniciamos el servicio de firewall
  systemd:
    name: firewalld
    state: reloaded

