---
#- name: Cambio permisos a root
#  environment:
#    KUBECONFIG: /etc/kubernetes/admin.conf

- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "KUBECONFIG="
    line: " KUBECONFIG=/etc/kubernetes/admin.conf"

- name: Creo directorios $HOME/.kube
  file:
    path: $HOME/.kube
    state: directory

- name: Copio archivo configuracion
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root
    group: root

