---

- name: 'Copio archivo Deploy service_account.yaml'
  copy:
    src: 'service_account.yaml'
    dest: '/root/kube_deploy/jenkins_ok/'

- name: Despliego Service Account
  command: 'kubectl apply -f /root/kube_deploy/jenkins_ok/service_account.yaml'
  register: result

- debug:
    msg: '{{ result }}'