---

- name: 'Copio archivo Deploy jenkins-services.yaml'
  copy:
    src: 'jenkins-services.yaml'
    dest: '/root/kube_deploy/jenkins_ok/'

- name: Despliego tls
  command: 'kubectl apply -f /root/kube_deploy/jenkins_ok/jenkins-services.yaml'
  register: result

- debug:
    msg: '{{ result }}'