---
- name: 'DEBUG - paquetes a instalar'
  debug:
    msg: 'Instalacion de CRI-O'

- name: Downlaod packages
  get_url:
    url: '{{ item.repo_url | mandatory}}'
    dest: '{{ item.repo_dest | mandatory}}'
  loop: '{{ repos | mandatory }}'


- name: 'Copio archivo para config CRI-O'
  copy:
    src: 'crio.conf'
    dest: '/etc/modules-load.d/'
  
- name: 'instalo CRI-O'
  dnf:
    name: 'cri-o'
    state: present

- name: 'Inicializa servicio y setea inicio automatico para servicio cri-o'
  systemd:
    name: 'crio'
    state: started
    enabled: yes


